server:
  port: 8082
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: oracle.jdbc.OracleDriver
      maximum-pool-size: 8
      connection-test-query: SELECT 1 FROM DUAL
      username: METRO
      password: 1234
    url: jdbc:oracle:thin:@192.168.10.12:1521:xe
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer


logging:
  level:
    com.hd: debug





